### PR TITLE
update CMakeLists to support newer versions

### PR DESCRIPTION
**Pull request by 3nids**

### CODE REVIEW

**Comment by m-kuhn** [comment]
why does it need qt widgets?

**Comment by 3nids** [comment]
Cmake was complaining and was giving this command as example.
I replaced Widgets by Core.

**Comment by m-kuhn** [comment]
Tesselate does not use Qt. Cmake is wrong.
Is it worth it to change this to silence cmake?

**Comment by 3nids** [comment]
image

**Comment by m-kuhn** [comment]
> Cmake is wrong.
>  Is it worth it to change this to silence cmake?

**Comment by 3nids** [comment]
Well, there is maybe a more clever way to tell cmake that tessellate does not require Qt. 

But to reply to your question, I guess no, it's not worth it.

**Comment by m-kuhn** [comment]
Maybe this one?

https://cmake.org/cmake/help/git-stage/prop_sf/SKIP_AUTOGEN.html#prop_sf:SKIP_AUTOGEN

**Comment by 3nids** [comment]
thanks for the hint, you can disable it for the whole target with set_property.

please squash if you merge.

**Review by m-kuhn — APPROVED** [review]

**Comment by m-kuhn** [comment]
Awesome!!

**Pull request merged**
